name: quiz
description: Practice with Quiz.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  riverpod: ^2.3.2
  flutter_riverpod: ^2.3.2
  go_router: ^6.5.0
  http: ^0.13.5
  shared_preferences: ^2.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  nock: ^1.2.1
